version: '3.8'
services:
  gateway:
    build:
      context: .
      dockerfile: ./DockerfileGateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      context: .
      dockerfile: ./DockerfileServer
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:14.2
    ports:
      - "6541:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: shareit
    volumes:
      - pg-data:/var/lib/postgresql/data/

volumes:
  pg-data: